name: animated_3D_button
description: A customizable animated 3D button with animated shadow effect
version: 1.0.0
homepage: https://github.com/imSap/animated_button

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
